# !/bin/bash
# set -e
# set -x

#pip install -r requirements.txt

# Note -- these are not the recommended settings for this dataset.  This is just so the open-source tests will finish quickly.

############## Preprecess the dataset
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'synset_X.pkl' --file-name "synset"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'biocyc205_tier23_9255_X.pkl' --file-name "biocyc205_tier23"

# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'golden_X.pkl' --file-name "golden"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'symbionts_X.pkl' --file-name "symbionts"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'hots_4_X.pkl' --file-name "hots_4"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'cami_X.pkl' --file-name "cami"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'gutcyc_X.pkl' --file-name "gutcyc"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'biocyc_X.pkl' --file-name "biocyc"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'biocyc21_X.pkl' --file-name "biocyc21"

# for pathway2vec paper
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_nv.pkl' --features-name 'path2vec_uec_nv_tf_embeddings.npz' --X-name 'biocyc205_tier23_9255_X.pkl' --file-name "synset1"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_nv.pkl' --features-name 'path2vec_uec_nv_tf_embeddings.npz' --X-name 'golden_X.pkl' --file-name "golden1"
#
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_mt.pkl' --features-name 'path2vec_uec_mt_tf_embeddings.npz' --X-name 'biocyc205_tier23_9255_X.pkl' --file-name "synset2"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_mt.pkl' --features-name 'path2vec_uec_mt_tf_embeddings.npz' --X-name 'golden_X.pkl' --file-name "golden2"
#
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'biocyc205_tier23_9255_X.pkl' --file-name "synset3"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'golden_X.pkl' --file-name "golden3"
#
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_jt.pkl' --features-name 'path2vec_uec_jt_tf_embeddings.npz' --X-name 'biocyc205_tier23_9255_X.pkl' --file-name "synset4"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_jt.pkl' --features-name 'path2vec_uec_jt_tf_embeddings.npz' --X-name 'golden_X.pkl' --file-name "golden4"
#
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_ex_33.pkl' --features-name 'path2vec_uec_ex_33_tf_embeddings.npz' --X-name 'biocyc205_tier23_9255_X.pkl' --file-name "synset5"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_ex_33.pkl' --features-name 'path2vec_uec_ex_33_tf_embeddings.npz' --X-name 'golden_X.pkl' --file-name "golden5"
#
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_ex_33.pkl' --features-name 'path2vec_uec_ex_33_10_tf_embeddings.npz' --X-name 'biocyc205_tier23_9255_X.pkl' --file-name "synset6"
# python main.py --preprocess-dataset --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --hin-name 'hin_uec_ex_33.pkl' --features-name 'path2vec_uec_ex_33_10_tf_embeddings.npz' --X-name 'golden_X.pkl' --file-name "golden6"

#######################################################################################################
###################################            First test           ###################################
#######################################################################################################
### optimum results for experiments

# results for elastic net
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --penalty "elasticnet" --alpha-elastic 0.0001 --l2-ratio 0.35 --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_e" --batch 50 --max-inner-iter 100 --num-epochs 10 --num-jobs 10

# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.1 --ssample-label-size 50 --calc-subsample-size 50 --penalty "elasticnet" --alpha-elastic 0.0001 --l2-ratio 0.35 --X-name 'synset1_Xe.pkl' --y-name 'biocyc205_tier23_9255_y.pkl' --file-name 'biocyc' --model-name "leADS_e1" --batch 50 --num-models 1 --max-inner-iter 10 --num-epochs 2 --num-jobs 20
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.1 --ssample-label-size 50 --calc-subsample-size 50 --penalty "elasticnet" --alpha-elastic 0.0001 --l2-ratio 0.35 --X-name 'synset2_Xe.pkl' --y-name 'biocyc205_tier23_9255_y.pkl' --file-name 'biocyc' --model-name "leADS_e2" --batch 50 --num-models 1 --max-inner-iter 10 --num-epochs 2 --num-jobs 20
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.1 --ssample-label-size 50 --calc-subsample-size 50 --penalty "elasticnet" --alpha-elastic 0.0001 --l2-ratio 0.35 --X-name 'synset3_Xe.pkl' --y-name 'biocyc205_tier23_9255_y.pkl' --file-name 'biocyc' --model-name "leADS_e3" --batch 50 --num-models 1 --max-inner-iter 10 --num-epochs 2 --num-jobs 20
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.1 --ssample-label-size 50 --calc-subsample-size 50 --penalty "elasticnet" --alpha-elastic 0.0001 --l2-ratio 0.35 --X-name 'synset4_Xe.pkl' --y-name 'biocyc205_tier23_9255_y.pkl' --file-name 'biocyc' --model-name "leADS_e4" --batch 50 --num-models 1 --max-inner-iter 10 --num-epochs 2 --num-jobs 20
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.1 --ssample-label-size 50 --calc-subsample-size 50 --penalty "elasticnet" --alpha-elastic 0.0001 --l2-ratio 0.35 --X-name 'synset5_Xe.pkl' --y-name 'biocyc205_tier23_9255_y.pkl' --file-name 'biocyc' --model-name "leADS_e5" --batch 50 --num-models 1 --max-inner-iter 10 --num-epochs 2 --num-jobs 20
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.1 --ssample-label-size 50 --calc-subsample-size 50 --penalty "elasticnet" --alpha-elastic 0.0001 --l2-ratio 0.35 --X-name 'synset6_Xe.pkl' --y-name 'biocyc205_tier23_9255_y.pkl' --file-name 'biocyc' --model-name "leADS_e6" --batch 50 --num-models 1 --max-inner-iter 10 --num-epochs 2 --num-jobs 20

# evaluate
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e_1' --model-name "leADS_e_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_e_2' --model-name "leADS_e_final" --num-jobs 15

# no binarize and neither normalize on BioCyc
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden1_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e1_1' --model-name "leADS_e1_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden2_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e2_1' --model-name "leADS_e2_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden3_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e3_1' --model-name "leADS_e3_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden4_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e4_1' --model-name "leADS_e4_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden5_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e5_1' --model-name "leADS_e5_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden6_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e6_1' --model-name "leADS_e6_final" --num-jobs 15

# no binarize and neither normalize on BioCyc
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden1_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e1_2' --model-name "leADS_e1_final" --num-jobs 1
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden2_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e2_2' --model-name "leADS_e2_final" --num-jobs 1
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden3_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e3_2' --model-name "leADS_e3_final" --num-jobs 1
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden4_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e4_2' --model-name "leADS_e4_final" --num-jobs 1
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden5_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e5_2' --model-name "leADS_e5_final" --num-jobs 1
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden6_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e6_2' --model-name "leADS_e6_final" --num-jobs 1

##### FINAL SHEOL
python main.py --train --train-labels --binarize --use-external-features --calc-ads --ads-percent 0.7 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 1.0 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --model-name "leADS_y" --batch 50 --num-models 3 --num-epochs 5 --num-jobs 15 --display-interval 1
python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_y_1' --model-name "leADS_y" --num-jobs 15
python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_y_2' --model-name "leADS_y" --num-jobs 15

python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.7 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 1.0 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --model-name "leADS_F" --batch 50 --num-models 3 --num-epochs 5 --num-jobs 15 --display-interval 1
python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_F_1' --model-name "leADS_F" --num-jobs 15
python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_F_2' --model-name "leADS_F" --num-jobs 15
python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_F_3' --model-name "leADS_F" --num-jobs 15
python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_F_4' --model-name "leADS_F" --num-jobs 15

python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'dependent' --ssample-input-size 1.0 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --model-name "leADS_D" --batch 50 --num-models 3 --num-epochs 1 --num-jobs 15 --display-interval 1
python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_D_samples.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --model-name "leADS_Dy" --batch 50 --num-epochs 10 --num-models 3 --num-jobs 20
python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_Dy_1' --model-name "leADS_Dy" --num-jobs 10
python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_Dy_2' --model-name "leADS_Dy" --num-jobs 10

#######################################################################################################
###################################           Second test           ###################################
#######################################################################################################
# based on 0.3 samples for reMap
# python main.py --train --binarize --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_1_B.pkl' --file-name 'biocyc' --model-name "leADS_3" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
# python main.py --train --binarize --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_4" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 20
# python main.py --train --binarize --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.npz' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_soap_collapsed" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 20
# python main.py --train --binarize --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_spreat_collapsed_bag_pathway.pkl' --features-name 'biocyc_spreat_collapsed_features.npz' --centroids 'biocyc_spreat_collapsed_bag_centroid.npz' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_3_B.pkl' --file-name 'biocyc' --model-name "leADS_spreat_collapsed" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 20

# python main.py --train --binarize --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_ctm_bag_pathway.pkl' --features-name 'biocyc_ctm_features.npz' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_4_3_B.pkl' --file-name 'biocyc' --model-name "leADS_ctm" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 20
# python main.py --train --binarize --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_soap_bag_pathway.pkl' --features-name 'biocyc_soap_features.npz' --centroids 'biocyc_soap_bag_centroid.npz' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_4_1_B.pkl' --file-name 'biocyc' --model-name "leADS_soap" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 20
# python main.py --train --binarize --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_spreat_bag_pathway.pkl' --features-name 'biocyc_spreat_features.npz' --centroids 'biocyc_spreat_bag_centroid.npz' --X-name 'biocyc_X.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_4_2_B.pkl' --file-name 'biocyc' --model-name "leADS_spreat" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 20

# evaluate
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_3_1'
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_3_2'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_3_3' --model-name "leADS_3_final" --num-jobs 15
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_3_4' --model-name "leADS_3_final" --num-jobs 15
## reports for reMap
# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_4_1' --model-name "leads/leADS_4_final" --num-jobs 1
# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_4_2' --model-name "leADS_4_final" --num-jobs 1
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_4_3' --model-name "leads/leADS_4_final" --num-jobs 1
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_4_4' --model-name "leADS_4_final" --num-jobs 1

## reports for SOAP
# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_soap_collapsed_1' --model-name "leADS_soap_collapsed" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_soap_collapsed_2' --model-name "leADS_soap_collapsed" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_soap_collapsed_3' --model-name "leADS_soap_collapsed" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_soap_collapsed_4' --model-name "leADS_soap_collapsed" --num-jobs 10

# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_spreat_collapsed_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_spreat_collapsed_1' --model-name "leADS_spreat_collapsed" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_spreat_collapsed_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_spreat_collapsed_2' --model-name "leADS_spreat_collapsed" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --bags-labels 'biocyc_spreat_collapsed_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_spreat_collapsed_3' --model-name "leADS_spreat_collapsed" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --bags-labels 'biocyc_spreat_collapsed_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_spreat_collapsed_4' --model-name "leADS_spreat_collapsed" --num-jobs 10

# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_ctm_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_ctm_1' --model-name "leADS_ctm" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_ctm_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_ctm_2' --model-name "leADS_ctm" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --bags-labels 'biocyc_ctm_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_ctm_3' --model-name "leADS_ctm" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --bags-labels 'biocyc_ctm_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_ctm_4' --model-name "leADS_ctm" --num-jobs 10

# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_soap_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_soap_1' --model-name "leADS_soap" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_soap_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_soap_2' --model-name "leADS_soap" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --bags-labels 'biocyc_soap_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_soap_3' --model-name "leADS_soap" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --bags-labels 'biocyc_soap_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_soap_4' --model-name "leADS_soap" --num-jobs 10

# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_spreat_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_spreat_1' --model-name "leADS_spreat" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --pref-rank --top-k-rank 200 --bags-labels 'biocyc_spreat_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_spreat_2' --model-name "leADS_spreat" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --bags-labels 'biocyc_spreat_bag_pathway.pkl' --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_spreat_3' --model-name "leADS_spreat" --num-jobs 10
# python main.py --evaluate --pred-labels --build-up --decision-threshold 0.5 --bags-labels 'biocyc_spreat_bag_pathway.pkl' --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_spreat_4' --model-name "leADS_spreat" --num-jobs 10

#######################################################################################################
###################################           Second test           ###################################
#######################################################################################################
# based on acquisition types on 0.3 samples for reMap and SOAP only
# [please add bags according to 50, 100, 150, 200, 300]; remember 200 is already trained
# python main.py --train --binarize --use-external-features --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_50_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_50_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_5_B.pkl' --file-name 'biocyc' --model-name "leADS_6" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
# python main.py --train --binarize --use-external-features --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_100_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_100_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_6_B.pkl' --file-name 'biocyc' --model-name "leADS_7" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
# python main.py --train --binarize --use-external-features --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_150_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_150_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_7_B.pkl' --file-name 'biocyc' --model-name "leADS_8" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
# python main.py --train --binarize --use-external-features --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_5" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
# python main.py --train --binarize --use-external-features --calc-bag-cost --label-uncertainty-type 'factorize' --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_300_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_300_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_8_B.pkl' --file-name 'biocyc' --model-name "leADS_9" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10

# evaluate
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_50_bag_pathway.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_6_1' --model-name "leADS_6_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_50_bag_pathway.pkl' --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_6_2' --model-name "leADS_6_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_6_3' --model-name "leADS_6_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_6_4' --model-name "leADS_6_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'

# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_100_bag_pathway.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_7_1' --model-name "leADS_7_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_100_bag_pathway.pkl' --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_7_2' --model-name "leADS_7_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_7_3' --model-name "leADS_7_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_7_4' --model-name "leADS_7_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'

# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_150_bag_pathway.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_8_1' --model-name "leADS_8_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_150_bag_pathway.pkl' --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_8_2' --model-name "leADS_8_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_8_3' --model-name "leADS_8_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_8_4' --model-name "leADS_8_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'

# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_5_1' --model-name "leADS_5_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_5_2' --model-name "leADS_5_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_5_3' --model-name "leADS_5_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_5_4' --model-name "leADS_5_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'

# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_300_bag_pathway.pkl' --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_9_1' --model-name "leADS_9_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --bags-labels 'biocyc_300_bag_pathway.pkl' --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_9_2' --model-name "leADS_9_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_9_3' --model-name "leADS_9_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_9_4' --model-name "leADS_9_final" --num-jobs 15 --mdpath '/Users/abdurrahman/Desktop/MetaPaIn/model/leads/'

#######################################################################################################
###################################            Third test           ###################################
#######################################################################################################
#  python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'entropy' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_10" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
#  python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'mutual' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_11" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_12" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'psp' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_13" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10

# train
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_10_samples.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_14" --batch 50 --num-epochs 3 --num-models 1 --num-jobs 10
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_11_samples.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_15" --batch 50 --num-epochs 3 --num-models 1 --num-jobs 10
## best on CAMI
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_12_samples.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_16" --batch 50 --num-epochs 3 --num-models 1 --num-jobs 10
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_13_samples.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_17" --batch 50 --num-epochs 3 --num-models 1 --num-jobs 10

#  python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'entropy' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_10_1" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
#  python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'mutual' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_11_1" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_12_1" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'psp' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_13_1" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 10

# evaluate
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --yB-name 'biocyc_B.pkl' --file-name 'leADS_14' --model-name "leADS_14_final" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --yB-name 'biocyc_B.pkl' --file-name 'leADS_15' --model-name "leADS_15_final" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --yB-name 'biocyc_B.pkl' --file-name 'leADS_16' --model-name "leADS_16_final" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --yB-name 'biocyc_B.pkl' --file-name 'leADS_17' --model-name "leADS_17_final" --num-jobs 10

# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_10_1' --model-name "leADS_10_1_final" --num-jobs 1
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_11_1' --model-name "leADS_11_1_final" --num-jobs 1
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_12_1' --model-name "leADS_12_1_final" --num-jobs 1
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_13_1' --model-name "leADS_13_1_final" --num-jobs 1

#######################################################################################################
###################################           Fourth test           ###################################
#######################################################################################################
# based on 'variation' we vary --ads-percent {0.3, 0.5, 0.7} for both 'dependent' and 'factorize'
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.5 --acquisition-type 'variation' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_18" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 15
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.7 --acquisition-type 'variation' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_19" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_20" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 15
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.5 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_21" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 15
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.7 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_22" --batch 50 --num-models 3 --num-epochs 10 --num-jobs 15

# train labels
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_18_samples_final.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_23" --batch 50 --num-epochs 3 --num-models 3 --num-jobs 15
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_19_samples_final.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_24" --batch 50 --num-epochs 3 --num-models 3 --num-jobs 20
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_20_samples_final.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_25" --batch 50 --num-epochs 3 --num-models 3 --num-jobs 15
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_21_samples_final.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_26" --batch 50 --num-epochs 3 --num-models 3 --num-jobs 15
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_22_samples_final.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_27" --batch 50 --num-epochs 10 --num-models 3 --num-jobs 15

# evaluate labels
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_23_1' --model-name "leADS_23_final" --num-jobs 10
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_23_2' --model-name "leADS_23_final" --num-jobs 10
#
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_24_1' --model-name "leADS_24_final" --num-jobs 10
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_24_2' --model-name "leADS_24_final" --num-jobs 10
#
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_25_1' --model-name "leADS_25_final" --num-jobs 10
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_25_2' --model-name "leADS_25_final" --num-jobs 10
#
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_26_1' --model-name "leADS_26_final" --num-jobs 10
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_26_2' --model-name "leADS_26_final" --num-jobs 10

# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_27_1' --model-name "leADS_27_final" --num-jobs 10
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_27_2' --model-name "leADS_27_final" --num-jobs 10

#######################################################################################################
###################################            Fifth test           ###################################
#######################################################################################################
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_28" --batch 50 --num-models 1 --num-epochs 2 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_29" --batch 50 --num-models 3 --num-epochs 2 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_30" --batch 50 --num-models 5 --num-epochs 2 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_31" --batch 50 --num-models 10 --num-epochs 2 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_32" --batch 50 --num-models 15 --num-epochs 2 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'factorize' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_33" --batch 50 --num-models 20 --num-epochs 2 --num-jobs 20

# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_28_1" --batch 50 --num-models 1 --num-epochs 2 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_29_1" --batch 50 --num-models 3 --num-epochs 2 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_30_1" --batch 50 --num-models 5 --num-epochs 2 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_31_1" --batch 50 --num-models 10 --num-epochs 2 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_32_1" --batch 50 --num-models 15 --num-epochs 2 --num-jobs 20
# python main.py --train --binarize --use-external-features --calc-bag-cost --calc-ads --ads-percent 0.3 --acquisition-type 'variation' --label-uncertainty-type 'dependent' --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl'  --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_33_1" --batch 50 --num-models 20 --num-epochs 2 --num-jobs 20

# train labels
# python main.py --train --train-selected-sample --binarize --use-external-features --calc-bag-cost --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_28_samples_final.pkl' --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_50" --batch 50 --num-epochs 5 --num-models 1 --num-jobs 10
# python main.py --train --train-selected-sample --binarize --use-external-features --calc-bag-cost --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_29_samples_final.pkl' --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_51" --batch 50 --num-epochs 5 --num-models 3 --num-jobs 10
# python main.py --train --train-selected-sample --binarize --use-external-features --calc-bag-cost --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_30_samples_final.pkl' --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_52" --batch 50 --num-epochs 5 --num-models 5 --num-jobs 10
# python main.py --train --train-selected-sample --binarize --use-external-features --calc-bag-cost --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_31_samples_final.pkl' --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_53" --batch 50 --num-epochs 5 --num-models 10 --num-jobs 10
# python main.py --train --train-selected-sample --binarize --use-external-features --calc-bag-cost --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_32_samples_final.pkl' --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_54" --batch 50 --num-epochs 5 --num-models 15 --num-jobs 10
# python main.py --train --train-selected-sample --binarize --use-external-features --calc-bag-cost --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_33_samples_final.pkl' --bags-labels 'biocyc_bag_pathway.pkl' --features-name 'biocyc_soap_features.pkl' --centroids 'biocyc_bag_centroid.npz' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --yB-name 'reMap_2_B.pkl' --file-name 'biocyc' --model-name "leADS_55" --batch 50 --num-epochs 5 --num-models 20 --num-jobs 10

# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_28_1_samples_final.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_57" --batch 50 --num-epochs 5 --num-models 1 --num-jobs 10
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_29_1_samples_final.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_58" --batch 50 --num-epochs 5 --num-models 3 --num-jobs 10
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_30_1_samples_final.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_59" --batch 50 --num-epochs 5 --num-models 5 --num-jobs 10
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_31_1_samples.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_60" --batch 50 --num-epochs 5 --num-models 10 --num-jobs 20
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_32_1_samples_final.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_61" --batch 50 --num-epochs 5 --num-models 15 --num-jobs 10
# python main.py --train --train-labels --train-selected-sample --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --samples-ids 'leADS_33_1_samples_final.pkl' --features-name 'biocyc_soap_features.pkl' --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_62" --batch 50 --num-epochs 5 --num-models 20 --num-jobs 10

# evaluate labels
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_50_1' --model-name "leADS_28" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_50_2' --model-name "leADS_28" --num-jobs 10
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_51_1' --model-name "leADS_51_final" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_51_2' --model-name "leADS_51_final" --num-jobs 10
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_52_1' --model-name "leADS_52" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_52_2' --model-name "leADS_52" --num-jobs 10
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_53_1' --model-name "leADS_53" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_53_2' --model-name "leADS_53" --num-jobs 10
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_54_1' --model-name "leADS_54_final" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_54_2' --model-name "leADS_54_final" --num-jobs 10
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 200 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_55_1' --model-name "leADS_55_final" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_55_2' --model-name "leADS_55_final" --num-jobs 10

# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_57_1' --model-name "leADS_57" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_58_1' --model-name "leADS_58" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_59_1' --model-name "leADS_59" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_60_1' --model-name "leADS_60" --num-jobs 20
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_61_1' --model-name "leADS_61" --num-jobs 10
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_62_1' --model-name "leADS_62" --num-jobs 10

#######################################################################################################
###################################            Sixth test           ###################################
#######################################################################################################
# train by varying models size in the ensemble
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_35" --batch 50 --num-models 1 --num-epochs 3 --num-jobs 15
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_36" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 15
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_37" --batch 50 --num-models 5 --num-epochs 3 --num-jobs 15
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_38" --batch 50 --num-models 10 --num-epochs 3 --num-jobs 15
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_39" --batch 50 --num-models 20 --num-epochs 3 --num-jobs 15
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_40" --batch 50 --num-models 50 --num-epochs 3 --num-jobs 15

# evaluate labels
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_35_1' --model-name "leADS_35_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_35_2' --model-name "leADS_35_final" --num-jobs 15
#
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_36_1' --model-name "leADS_36_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_36_2' --model-name "leADS_36_final" --num-jobs 15
#
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_37_1' --model-name "leADS_37_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_37_2' --model-name "leADS_37_final" --num-jobs 15

# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_38_1' --model-name "leADS_38_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_38_2' --model-name "leADS_38_final" --num-jobs 15

# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_39_1' --model-name "leADS_39_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_39_2' --model-name "leADS_39_final" --num-jobs 15

# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_40_1' --model-name "leADS_40_final" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_40_2' --model-name "leADS_40_final" --num-jobs 15

#######################################################################################################
###################################          Seventh test           ###################################
#######################################################################################################
# train using random allocation of biocyc varying {0.3,0.5,0.7},
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.3 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_41" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 20
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.5 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_42" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 20
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 50 --calc-subsample-size 50 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc_Xe.pkl' --y-name 'biocyc_y.pkl' --file-name 'biocyc' --model-name "leADS_43" --batch 50 --num-models 3 --num-epochs 3 --num-jobs 20
#
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_41_1' --model-name "leADS_41" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_41_2' --model-name "leADS_41" --num-jobs 15
#
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_42_1' --model-name "leADS_42" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_42_2' --model-name "leADS_42" --num-jobs 15
#
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_43_1' --model-name "leADS_43" --num-jobs 15
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_43_2' --model-name "leADS_43" --num-jobs 15

#######################################################################################################
###################################          DETAIL REPORT          ###################################
#######################################################################################################
## evaluate
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'symbionts_Xe.pkl' --y-name 'symbionts_y.pkl' --file-name 'leADS_y_symbionts' --model-name "leads/leADS_y_final" --num-jobs 1
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'hots_4_Xe.pkl' --y-name 'hots_4_y.pkl' --file-name 'leADS_y_hots_4' --model-name "leads/leADS_y_final" --num-jobs 1

# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 100 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'symbionts_Xe.pkl' --y-name 'symbionts_y.pkl' --file-name 'leADS_B1_symbionts' --model-name "leads/leADS_B_final" --num-jobs 1
# python main.py --evaluate --pred-labels --pref-rank --top-k-rank 300 --bags-labels 'biocyc_bag_pathway.pkl' --X-name 'hots_4_Xe.pkl' --y-name 'hots_4_y.pkl' --file-name 'leADS_B1_hots_4' --model-name "leads/leADS_B_final" --num-jobs 1

# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'symbionts_Xe.pkl' --y-name 'symbionts_y.pkl' --file-name 'leADS_B2_symbionts' --model-name "leads/leADS_B_final" --num-jobs 1
# python main.py --evaluate --pred-labels --decision-threshold 0.5 --X-name 'hots_4_Xe.pkl' --y-name 'hots_4_y.pkl' --file-name 'leADS_B2_hots_4' --model-name "leads/leADS_B_final" --num-jobs 1

## predict
# python main.py --predict --pred-labels --detail-report --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --X-name 'symbionts_X.pkl' --file-name "leads_4_symbionts" --model-name "leads/leADS_4_final" --rsfolder "leADS_4_symbionts" --num-jobs 1
# python main.py --predict --pred-labels --detail-report --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --X-name 'hots_4_X.pkl' --file-name "leads_4_hots" --model-name "leads/leADS_4_final" --rsfolder "leADS_4_hots" --batch 50 --num-jobs 1

# python main.py --predict --pathway-report --no-parse --no-build-features --pred-labels --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'symbionts_Xe.pkl' --file-name "leads_y_symbionts" --model-name "leads/leADS_y_final" --rsfolder "leads_y_symbionts" --batch 50 --num-jobs 1
# python main.py --predict --pathway-report --no-parse --no-build-features --pred-labels --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'hots_4_Xe.pkl' --file-name "leads_y_hots" --model-name "leads/leADS_y_final" --rsfolder "leADS_y_hots" --batch 50 --num-jobs 1

# python main.py --predict --pred-labels --detail-report --pref-rank --top-k-rank 100 --bags-labels 'biocyc_bag_pathway.pkl' --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --X-name 'symbionts_Xe.pkl' --file-name "leads_B_symbionts" --model-name "leads/leADS_B_final" --rsfolder "leADS_B1_symbionts" --num-jobs 1
# python main.py --predict --pred-labels --detail-report --pref-rank --top-k-rank 300 --bags-labels 'biocyc_bag_pathway.pkl' --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --X-name 'hots_4_Xe.pkl' --file-name "leads_B_hots" --model-name "leads/leADS_B_final" --rsfolder "leADS_B1_hots" --num-jobs 1

# python main.py --predict --pred-labels --detail-report --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --X-name 'symbionts_Xe.pkl' --file-name "leads_B_symbionts" --model-name "leads/leADS_B_final" --rsfolder "leADS_B2_symbionts" --num-jobs 1
# python main.py --predict --pred-labels --detail-report --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-name 'pathway2ec.pkl' --X-name 'hots_4_Xe.pkl' --file-name "leads_B_symbionts" --model-name "leads/leADS_B_final" --rsfolder "leADS_B2_hots" --batch 50 --num-jobs 1

#######################################################################################################
###################################          FINAL PUBLIC           ###################################
#######################################################################################################
# python main.py --train --train-labels --ssample-input-size 0.7 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc21_X.pkl' --y-name 'biocyc21_y.pkl' --model-name "leADS_X" --batch 50 --num-models 3 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_X.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_X_1' --model-name "leADS_X" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_X.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_X_2' --model-name "leADS_X" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'sag_X.pkl' --y-name 'sag_y.pkl' --file-name 'leADS_X_3' --model-name "leADS_X" --num-jobs 20
#
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc21_Xe.pkl' --y-name 'biocyc21_y.pkl' --model-name "leADS_e" --batch 50 --num-models 3 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xe.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_e_1' --model-name "leADS_e" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xe.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_e_2' --model-name "leADS_e" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'sag_Xe.pkl' --y-name 'sag_y.pkl' --file-name 'leADS_e_3' --model-name "leADS_e" --num-jobs 20
#
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc21_Xa.pkl' --y-name 'biocyc21_y.pkl' --model-name "leADS_a" --batch 50 --num-models 3 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xa.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_a_1' --model-name "leADS_a" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xa.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_a_2' --model-name "leADS_a" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'sag_Xa.pkl' --y-name 'sag_y.pkl' --file-name 'leADS_a_3' --model-name "leADS_a" --num-jobs 20
#
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc21_Xc.pkl' --y-name 'biocyc21_y.pkl' --model-name "leADS_c" --batch 50 --num-models 3 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xc.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_c_1' --model-name "leADS_c" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xc.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_c_2' --model-name "leADS_c" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'sag_Xc.pkl' --y-name 'sag_y.pkl' --file-name 'leADS_c_3' --model-name "leADS_c" --num-jobs 20
#
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc21_Xea.pkl' --y-name 'biocyc21_y.pkl' --model-name "leADS_ea" --batch 50 --num-models 3 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xea.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_ea_1' --model-name "leADS_ea" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xea.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_ea_2' --model-name "leADS_ea" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'sag_Xea.pkl' --y-name 'sag_y.pkl' --file-name 'leADS_ea_3' --model-name "leADS_ea" --num-jobs 20
#
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc21_Xec.pkl' --y-name 'biocyc21_y.pkl' --model-name "leADS_ec" --batch 50 --num-models 3 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xec.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_ec_1' --model-name "leADS_ec" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xec.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_ec_2' --model-name "leADS_ec" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'sag_Xec.pkl' --y-name 'sag_y.pkl' --file-name 'leADS_ec_3' --model-name "leADS_ec" --num-jobs 20
#
# python main.py --train --train-labels --binarize --use-external-features --ssample-input-size 0.7 --ssample-label-size 3000 --calc-subsample-size 500 --lambdas 0.01 0.01 0.01 0.01 0.01 10 --penalty "l21" --X-name 'biocyc21_Xm.pkl' --y-name 'biocyc21_y.pkl' --model-name "leADS_m" --batch 50 --num-models 3 --num-epochs 10 --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'golden_Xm.pkl' --y-name 'golden_y.pkl' --file-name 'leADS_m_1' --model-name "leADS_m" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'cami_Xm.pkl' --y-name 'cami_y.pkl' --file-name 'leADS_m_2' --model-name "leADS_m" --num-jobs 20
# python main.py --evaluate --pred-labels --soft-voting --decision-threshold 0.5 --X-name 'sag_Xm.pkl' --y-name 'sag_y.pkl' --file-name 'leADS_m_3' --model-name "leADS_m" --num-jobs 20

# python main.py --predict --pathway-report --pred-labels --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_X.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "leADS_X" --dsfolder "/mnt/nfs/sharknado/LimsData/Hallam_Databases/formatted/Saanich_SAGs/PGDBs_v21" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "leADS_SAG_X" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
# python main.py --predict --pathway-report --no-parse --no-build-features --pred-labels --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xe.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "leADS_e" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "leADS_SAG_E" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
# python main.py --predict --pathway-report --no-parse --no-build-features --pred-labels --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xa.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "leADS_a" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "leADS_SAG_A" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
# python main.py --predict --pathway-report --no-parse --no-build-features --pred-labels --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xc.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "leADS_c" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "leADS_SAG_C" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
# python main.py --predict --pathway-report --no-parse --no-build-features --pred-labels --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xea.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "leADS_ea" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "leADS_SAG_EA" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
# python main.py --predict --pathway-report --no-parse --no-build-features --pred-labels --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xec.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "leADS_ec" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "leADS_SAG_EC" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
# python main.py --predict --pathway-report --no-parse --no-build-features --pred-labels --soft-voting --decision-threshold 0.5 --object-name "biocyc.pkl" --pathway2ec-idx-name "pathway2ec_idx.pkl" --pathway2ec-name 'pathway2ec.pkl' --hin-name 'hin_cmt.pkl' --features-name 'path2vec_cmt_tf_embeddings.npz' --X-name 'SAG_Xm.pkl' --samples-ids 'SAG_ids.pkl' --file-name "SAG" --model-name "leADS_m" --dspath "/home/abdurrahman/MetaPaIn/dataset" --rsfolder "leADS_SAG_M" --rspath "/home/abdurrahman/MetaPaIn/result" --batch 50 --num-jobs 15
